name: Deploy EC2 in multiple AWS accounts

on:
  push:
    branches: [ "main"]

env:
  AWS_REGION_1_DEV: "us-east-1"
  AWS_REGION_2_PROD: "ap-south-1"
  AWS_ACCOUNT_ID_1_DEV: "730335175099" # Replace with your first AWS account ID
  AWS_ACCOUNT_ID_2_PROD: "666562444707" # Replace with your second AWS account ID

permissions:
  id-token: write
  contents: read

jobs:
  terraform-aws-dev:
    name: Deploying on Dev env
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials DEV env
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID_1_DEV }}:role/env_dev_oidc_github_role # Replace with your IAM role ARN
          aws-region: ${{ env.AWS_REGION_1_DEV }}
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        working-directory: dev
        run: terraform init

      - name: Apply Terraform
        working-directory: dev
        run: terraform apply -auto-approve

  terraform-aws-prod:
    name: Deploying on PROD env
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials for PROD env
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID_2_PROD }}:role/env_prod_oidc_github_role # Replace with your IAM role ARN
          aws-region: ${{ env.AWS_REGION_2_PROD }}
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        working-directory: prod
        run: terraform init

      - name: Apply Terraform
        working-directory: prod
        run: terraform apply -auto-approve
