name: Deploy EC2 in multiple AWS accounts

on:
  push:
    branches: [ "main"]

env:
  AWS_REGION_1_DEV: "us-east-1"
  AWS_REGION_1_DEV_ROLE_NAME: "env_dev_oidc_github_role"
  AWS_REGION_2_PROD: "ap-south-1"
  AWS_REGION_2_PROD_ROLE_NAME: "env_prod_oidc_github_role"
  AWS_ACCOUNT_ID_1_DEV: "730335175099" # Replace with your first AWS account ID
  AWS_ACCOUNT_ID_2_PROD: "666562444707" # Replace with your second AWS account ID

permissions:
  id-token: write
  contents: read

jobs:
  terraform-aws-dev:
    name: Deploying on Dev env
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials DEV env
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID_1_DEV }}:role/${{ env.AWS_REGION_1_DEV_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION_1_DEV }}
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
  
      - name: Initialize Terraform
        working-directory: awsdev
        run: terraform init
        
      - name: Terraform Plan
        id: plan
        working-directory: awsdev
        run: terraform plan -out=tfplan-${{ github.sha }}

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ github.sha }}
          path: awsdev/tfplan-${{ github.sha }}

      - name: Apply Terraform
        if: success()
        working-directory: awsdev
        run: terraform apply -auto-approve tfplan-${{ github.sha }}

  terraform-aws-prod:
    name: Deploying on PROD env
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials for PROD env
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID_2_PROD }}:role/${{ env.AWS_REGION_2_PROD_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION_2_PROD }}
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        working-directory: awsprod
        run: terraform init
        
      - name: Terraform Plan
        id: plan
        working-directory: awsprod
        run: terraform plan -out=tfplan-${{ github.sha }}

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ github.sha }}
          path: awsprod/tfplan-${{ github.sha }}

      - name: Apply Terraform
        if: success()
        working-directory: awsprod
        run: terraform apply -auto-approve tfplan-${{ github.sha }}